---
title: "Homework 4"
---

## Instructions

Please complete this assignment by creating a new RMarkdown (or Quarto) file. Be sure to include your name in the preamble. Please submit both your .Rmd (or .qmd) and your .html files to Canvas.


**Data:** These data were from a study where physical health was predicted by a happiness measure, socioeconomic status, number of close friends, and a 16-week mood intervention with a waitlist control group (coded 0), a positive self affirmation intervention group (coded 1), and a meditation group (coded 2). The data are here: [`th-project-3.csv`](th-project-3.csv)

## Homework Questions

1. Perform a multiple regression where health is regressed on (predicted by) friends, SES, and happiness. Interpret each regression coefficient. 

2. Graph the (2-d) relationship between health and happiness as found in the above regression. Make sure the association controls for the remaining variables in the model. Include data points in your graph and a confidence band. 

3. Describe why the confidence band looks like a bow tie in the above graph. 

4. For the above regression, calculate the variance explained using the ANOVA table and interpret the residual standard error.  

5. Add the group variable `mood.group` into the regression model from #2. Then answer the following:

    a. Interpret the coefficients
    b. Is there a significant increase in variance explained compared to the initial regression in #1? If so, what is the estimate? 


