---
title: "hw 6"
---

Due: 3/4 at 9:59am

**Data:**  The data consist of a 2x3 anova design examining comics. The two factors are: 1) Publisher, which has two levels (DC or Marvel comics). 2) is Alignment, which has three levels (good, bad, neutral). The DV is Total, which is a combination of strength, intelligence, speed, durability, power, and combat. Higher scores are better. 

The research question is whether there are differences in total across publisher, across type of superhereo alignment and whether there is an interaction between these two factors. Data can be found here: [`hw-6-data.csv`](superhero.csv)  

Remember that if you work with a peer or use AI tools like Chat-GPT, you must cite them in your code. 

You will submit both your .Rmd/.qmd and HTML files to Canvas. For all figures, you must be intentional. Change the axes names, the theme etc. Do not settle for the defaults!

Good luck!

1. Write the equation that you will use to test the hypothesis. Run this in R and interpret what each of the coefficients mean. 

2. Are there any significant differences between?  
  a. Good and bad? 
  b. DC vs Marvel
  c. DC bad superheros vs Marvel bad superheros
  d. DC neutral vs DC bad

3. What are the standardized (cohen's d) differences between the groups in #2? 

4. Create two graphs. 1. that show cell differences between groups. 2. that show differences in one of the marginal means. 
